name: Build LaTeX examples

env:
  repo_dir: "koltin-latex"
  example_file: "kotlin_example"

on:
  push:
    paths:
      - "**/*.tex"
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          path: "${{ env.repo_dir }}"

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "${{ env.repo_dir }}/example"
          root_file: "${{ env.example_file }}.tex"

      # upload workflow
      - name: Upload LaTeX documents
        uses: actions/upload-artifact@v2
        with:
          name: Examples
          path: |
            "${{ env.repo_dir }}/example/*.pdf"
            "${{ env.repo_dir }}/readme/*.png"

      - name: Convert to PDF to PNG
        run: |
          sudo apt install poppler-utils
          pdftoppm -cropbox -png "${{ env.repo_dir }}/example/${{ env.example_file }}.pdf" "${{ env.repo_dir }}/example/example"
          ls -la "${{ env.repo_dir }}/example/"
          mv -f "${{ env.repo_dir }}/example/example-01.png" "${{ env.repo_dir }}/readme/simple.png"
          mv -f "${{ env.repo_dir }}/example/example-02.png" "${{ env.repo_dir }}/readme/example.png"

      # upload dist
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ env.repo_dir }}/example/${{ env.example_file }}.pdf"
          tag: ${{ env.tag }}
          release_name: "Example"
          body: "Example pdf of the current commit."
          overwrite: true
          file_glob: true